### ISSUE TITLE
Stuck in Infinite loop.

### ISSUE THREAD

**Issue by pawanspace** [pcorey/elixir_poster#2]
I am trying to use it with some snippet of code and elixir logo. Its stuck in some infinite loop. will be good to know if code should be in particular format or language. how big should be the code file?

**Comment by pcorey** [comment]
I updated the README with a few more specifics about the resolutions to use. Definitely use a small image. a `389`x`300` px source images takes approximately 60 seconds to generate the final SVG on my machine.
